name: Publish to PyPI
on:
  push:
    branches:
      - master

jobs:
  build-n-publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Create virtual env
      run: >-
        python3 -m
        venv
        venv
    - name: Activate virtual env
      run: >-
        source venv/bin/activate
    - name: Download dependencies
      run: >-
        python -m pip install build twine poetry
    - name: Build
      run: >-
        python -m build
    - name: Publish
      env:
        TWINE_USERNAME: __token__
        TWINE_PASSWORD: ${{ secrets.PYPI_API_TOKEN }}
      run: >-
        twine upload dist/* --verbose
    # - name: Publish distribution 📦 to Test PyPI
    #   uses: pypa/gh-action-pypi-publish@release/v1
    #   with:
    #     password: ${{ secrets.TEST_PYPI_API_TOKEN }}
    #     repository_url: https://test.pypi.org/legacy/
    # - name: Publish distribution 📦 to PyPI
    #   if: startsWith(github.ref, 'refs/tags')
    #   uses: pypa/gh-action-pypi-publish@release/v1
    #   with:
    #     password: ${{ secrets.PYPI_API_TOKEN }}